#!/bin/bash

BINDIR=/usr/local/bin
DATADIR=$1
CERTDIR=$DATADIR/certs
COCKROACH=$BINDIR/cockroach
HOST=$2
DATABASE=$3

$COCKROACH sql 	\
		--certs-dir=$CERTDIR \
		--host=$HOST <<EOF
CREATE DATABASE IF NOT EXISTS $DATABASE;
CREATE USER IF NOT EXISTS $DATABASE WITH PASSWORD '$DATABASE';
GRANT ALL ON DATABASE $DATABASE TO $DATABASE;
EOF