#!/bin/bash

BINDIR=/usr/local/bin
COCKROACH=$BINDIR/cockroach
DATADIR=$1
CERTDIR=$2
HOST=$3
DATABASE=$4

$COCKROACH sql 	\
		--certs-dir=$CERTDIR \
		--host=$HOST <<EOF
CREATE DATABASE IF NOT EXISTS $DATABASE;
CREATE USER IF NOT EXISTS $DATABASE WITH PASSWORD '$DATABASE';
GRANT ALL ON DATABASE $DATABASE TO $DATABASE;
EOF