#!/bin/bash

BINDIR=/usr/local/bin
COCKROACH=$BINDIR/cockroach
CERTDIR=$1
HOST=$2
DATABASE=$3
PASSWORD=$4

$COCKROACH sql 	\
		--certs-dir=$CERTDIR \
		--host=$HOST <<EOF
CREATE DATABASE IF NOT EXISTS $DATABASE;
CREATE USER IF NOT EXISTS $DATABASE WITH PASSWORD '$PASSWORD';
GRANT ALL ON DATABASE $DATABASE TO $DATABASE;
EOF