// Code generated by protoc-gen-go. DO NOT EDIT.
// source: connectorCommand.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CommandMessage struct {
	SourceAggregator      string   `protobuf:"bytes,1,opt,name=SourceAggregator,json=sourceAggregator,proto3" json:"SourceAggregator,omitempty"`
	SourceConnector       string   `protobuf:"bytes,2,opt,name=SourceConnector,json=sourceConnector,proto3" json:"SourceConnector,omitempty"`
	SourceWorker          string   `protobuf:"bytes,3,opt,name=SourceWorker,json=sourceWorker,proto3" json:"SourceWorker,omitempty"`
	DestinationAggregator string   `protobuf:"bytes,4,opt,name=DestinationAggregator,json=destinationAggregator,proto3" json:"DestinationAggregator,omitempty"`
	DestinationConnector  string   `protobuf:"bytes,5,opt,name=DestinationConnector,json=destinationConnector,proto3" json:"DestinationConnector,omitempty"`
	DestinationWorker     string   `protobuf:"bytes,6,opt,name=DestinationWorker,json=destinationWorker,proto3" json:"DestinationWorker,omitempty"`
	Tenant                string   `protobuf:"bytes,7,opt,name=Tenant,json=tenant,proto3" json:"Tenant,omitempty"`
	Token                 string   `protobuf:"bytes,8,opt,name=Token,json=token,proto3" json:"Token,omitempty"`
	Context               string   `protobuf:"bytes,9,opt,name=Context,json=context,proto3" json:"Context,omitempty"`
	Timeout               string   `protobuf:"bytes,10,opt,name=Timeout,json=timeout,proto3" json:"Timeout,omitempty"`
	Timestamp             string   `protobuf:"bytes,11,opt,name=Timestamp,json=timestamp,proto3" json:"Timestamp,omitempty"`
	Major                 string   `protobuf:"bytes,12,opt,name=Major,json=major,proto3" json:"Major,omitempty"`
	Minor                 string   `protobuf:"bytes,13,opt,name=Minor,json=minor,proto3" json:"Minor,omitempty"`
	Uuid                  string   `protobuf:"bytes,14,opt,name=Uuid,json=uuid,proto3" json:"Uuid,omitempty"`
	ConnectorType         string   `protobuf:"bytes,15,opt,name=ConnectorType,json=connectorType,proto3" json:"ConnectorType,omitempty"`
	CommandType           string   `protobuf:"bytes,16,opt,name=CommandType,json=commandType,proto3" json:"CommandType,omitempty"`
	Command               string   `protobuf:"bytes,17,opt,name=Command,json=command,proto3" json:"Command,omitempty"`
	Payload               string   `protobuf:"bytes,18,opt,name=Payload,json=payload,proto3" json:"Payload,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *CommandMessage) Reset()         { *m = CommandMessage{} }
func (m *CommandMessage) String() string { return proto.CompactTextString(m) }
func (*CommandMessage) ProtoMessage()    {}
func (*CommandMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_84ea62e0fbc109bd, []int{0}
}

func (m *CommandMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandMessage.Unmarshal(m, b)
}
func (m *CommandMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandMessage.Marshal(b, m, deterministic)
}
func (m *CommandMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandMessage.Merge(m, src)
}
func (m *CommandMessage) XXX_Size() int {
	return xxx_messageInfo_CommandMessage.Size(m)
}
func (m *CommandMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CommandMessage proto.InternalMessageInfo

func (m *CommandMessage) GetSourceAggregator() string {
	if m != nil {
		return m.SourceAggregator
	}
	return ""
}

func (m *CommandMessage) GetSourceConnector() string {
	if m != nil {
		return m.SourceConnector
	}
	return ""
}

func (m *CommandMessage) GetSourceWorker() string {
	if m != nil {
		return m.SourceWorker
	}
	return ""
}

func (m *CommandMessage) GetDestinationAggregator() string {
	if m != nil {
		return m.DestinationAggregator
	}
	return ""
}

func (m *CommandMessage) GetDestinationConnector() string {
	if m != nil {
		return m.DestinationConnector
	}
	return ""
}

func (m *CommandMessage) GetDestinationWorker() string {
	if m != nil {
		return m.DestinationWorker
	}
	return ""
}

func (m *CommandMessage) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *CommandMessage) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CommandMessage) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *CommandMessage) GetTimeout() string {
	if m != nil {
		return m.Timeout
	}
	return ""
}

func (m *CommandMessage) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *CommandMessage) GetMajor() string {
	if m != nil {
		return m.Major
	}
	return ""
}

func (m *CommandMessage) GetMinor() string {
	if m != nil {
		return m.Minor
	}
	return ""
}

func (m *CommandMessage) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *CommandMessage) GetConnectorType() string {
	if m != nil {
		return m.ConnectorType
	}
	return ""
}

func (m *CommandMessage) GetCommandType() string {
	if m != nil {
		return m.CommandType
	}
	return ""
}

func (m *CommandMessage) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *CommandMessage) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type CommandMessageUUID struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=Uuid,json=uuid,proto3" json:"Uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandMessageUUID) Reset()         { *m = CommandMessageUUID{} }
func (m *CommandMessageUUID) String() string { return proto.CompactTextString(m) }
func (*CommandMessageUUID) ProtoMessage()    {}
func (*CommandMessageUUID) Descriptor() ([]byte, []int) {
	return fileDescriptor_84ea62e0fbc109bd, []int{1}
}

func (m *CommandMessageUUID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandMessageUUID.Unmarshal(m, b)
}
func (m *CommandMessageUUID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandMessageUUID.Marshal(b, m, deterministic)
}
func (m *CommandMessageUUID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandMessageUUID.Merge(m, src)
}
func (m *CommandMessageUUID) XXX_Size() int {
	return xxx_messageInfo_CommandMessageUUID.Size(m)
}
func (m *CommandMessageUUID) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandMessageUUID.DiscardUnknown(m)
}

var xxx_messageInfo_CommandMessageUUID proto.InternalMessageInfo

func (m *CommandMessageUUID) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type CommandMessageWait struct {
	WorkerSource         string   `protobuf:"bytes,1,opt,name=WorkerSource,json=workerSource,proto3" json:"WorkerSource,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,json=value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandMessageWait) Reset()         { *m = CommandMessageWait{} }
func (m *CommandMessageWait) String() string { return proto.CompactTextString(m) }
func (*CommandMessageWait) ProtoMessage()    {}
func (*CommandMessageWait) Descriptor() ([]byte, []int) {
	return fileDescriptor_84ea62e0fbc109bd, []int{2}
}

func (m *CommandMessageWait) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandMessageWait.Unmarshal(m, b)
}
func (m *CommandMessageWait) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandMessageWait.Marshal(b, m, deterministic)
}
func (m *CommandMessageWait) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandMessageWait.Merge(m, src)
}
func (m *CommandMessageWait) XXX_Size() int {
	return xxx_messageInfo_CommandMessageWait.Size(m)
}
func (m *CommandMessageWait) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandMessageWait.DiscardUnknown(m)
}

var xxx_messageInfo_CommandMessageWait proto.InternalMessageInfo

func (m *CommandMessageWait) GetWorkerSource() string {
	if m != nil {
		return m.WorkerSource
	}
	return ""
}

func (m *CommandMessageWait) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type CommandMessageReply struct {
	SourceAggregator      string   `protobuf:"bytes,1,opt,name=SourceAggregator,json=sourceAggregator,proto3" json:"SourceAggregator,omitempty"`
	SourceConnector       string   `protobuf:"bytes,2,opt,name=SourceConnector,json=sourceConnector,proto3" json:"SourceConnector,omitempty"`
	SourceWorker          string   `protobuf:"bytes,3,opt,name=SourceWorker,json=sourceWorker,proto3" json:"SourceWorker,omitempty"`
	DestinationAggregator string   `protobuf:"bytes,4,opt,name=DestinationAggregator,json=destinationAggregator,proto3" json:"DestinationAggregator,omitempty"`
	DestinationConnector  string   `protobuf:"bytes,5,opt,name=DestinationConnector,json=destinationConnector,proto3" json:"DestinationConnector,omitempty"`
	DestinationWorker     string   `protobuf:"bytes,6,opt,name=DestinationWorker,json=destinationWorker,proto3" json:"DestinationWorker,omitempty"`
	Tenant                string   `protobuf:"bytes,7,opt,name=Tenant,json=tenant,proto3" json:"Tenant,omitempty"`
	Token                 string   `protobuf:"bytes,8,opt,name=Token,json=token,proto3" json:"Token,omitempty"`
	Context               string   `protobuf:"bytes,9,opt,name=Context,json=context,proto3" json:"Context,omitempty"`
	Timeout               string   `protobuf:"bytes,10,opt,name=Timeout,json=timeout,proto3" json:"Timeout,omitempty"`
	Timestamp             string   `protobuf:"bytes,11,opt,name=Timestamp,json=timestamp,proto3" json:"Timestamp,omitempty"`
	Uuid                  string   `protobuf:"bytes,12,opt,name=Uuid,json=uuid,proto3" json:"Uuid,omitempty"`
	Reply                 string   `protobuf:"bytes,13,opt,name=Reply,json=reply,proto3" json:"Reply,omitempty"`
	Payload               string   `protobuf:"bytes,14,opt,name=Payload,json=payload,proto3" json:"Payload,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *CommandMessageReply) Reset()         { *m = CommandMessageReply{} }
func (m *CommandMessageReply) String() string { return proto.CompactTextString(m) }
func (*CommandMessageReply) ProtoMessage()    {}
func (*CommandMessageReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84ea62e0fbc109bd, []int{3}
}

func (m *CommandMessageReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandMessageReply.Unmarshal(m, b)
}
func (m *CommandMessageReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandMessageReply.Marshal(b, m, deterministic)
}
func (m *CommandMessageReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandMessageReply.Merge(m, src)
}
func (m *CommandMessageReply) XXX_Size() int {
	return xxx_messageInfo_CommandMessageReply.Size(m)
}
func (m *CommandMessageReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandMessageReply.DiscardUnknown(m)
}

var xxx_messageInfo_CommandMessageReply proto.InternalMessageInfo

func (m *CommandMessageReply) GetSourceAggregator() string {
	if m != nil {
		return m.SourceAggregator
	}
	return ""
}

func (m *CommandMessageReply) GetSourceConnector() string {
	if m != nil {
		return m.SourceConnector
	}
	return ""
}

func (m *CommandMessageReply) GetSourceWorker() string {
	if m != nil {
		return m.SourceWorker
	}
	return ""
}

func (m *CommandMessageReply) GetDestinationAggregator() string {
	if m != nil {
		return m.DestinationAggregator
	}
	return ""
}

func (m *CommandMessageReply) GetDestinationConnector() string {
	if m != nil {
		return m.DestinationConnector
	}
	return ""
}

func (m *CommandMessageReply) GetDestinationWorker() string {
	if m != nil {
		return m.DestinationWorker
	}
	return ""
}

func (m *CommandMessageReply) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *CommandMessageReply) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CommandMessageReply) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *CommandMessageReply) GetTimeout() string {
	if m != nil {
		return m.Timeout
	}
	return ""
}

func (m *CommandMessageReply) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *CommandMessageReply) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *CommandMessageReply) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func (m *CommandMessageReply) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func init() {
	proto.RegisterType((*CommandMessage)(nil), "grpc.CommandMessage")
	proto.RegisterType((*CommandMessageUUID)(nil), "grpc.CommandMessageUUID")
	proto.RegisterType((*CommandMessageWait)(nil), "grpc.CommandMessageWait")
	proto.RegisterType((*CommandMessageReply)(nil), "grpc.CommandMessageReply")
}

func init() { proto.RegisterFile("connectorCommand.proto", fileDescriptor_84ea62e0fbc109bd) }

var fileDescriptor_84ea62e0fbc109bd = []byte{
	// 552 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x55, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x6e, 0xb7, 0xfe, 0xd0, 0xd3, 0xff, 0x43, 0xb7, 0x99, 0x8a, 0x8b, 0x29, 0xe2, 0xa2, 0x42,
	0xa8, 0x17, 0x83, 0x17, 0x60, 0x1d, 0x48, 0x5c, 0x0c, 0x55, 0x5b, 0xcb, 0xae, 0x4d, 0x62, 0x55,
	0x61, 0x8d, 0x1d, 0x39, 0x0e, 0xac, 0x8f, 0xc6, 0xcb, 0xf0, 0x02, 0xbc, 0x04, 0xf2, 0x71, 0xda,
	0xa6, 0x59, 0x76, 0xcf, 0xc5, 0x2e, 0xbf, 0x9f, 0x63, 0x7f, 0x8e, 0x3f, 0x39, 0x70, 0xea, 0x2b,
	0x29, 0x85, 0x6f, 0x94, 0x9e, 0xa9, 0x28, 0xe2, 0x32, 0x98, 0xc6, 0x5a, 0x19, 0x85, 0xb5, 0x95,
	0x8e, 0xfd, 0x71, 0x37, 0x12, 0x49, 0xc2, 0x57, 0xc2, 0x91, 0xde, 0x9f, 0x1a, 0xf4, 0x32, 0xdb,
	0xb5, 0x13, 0xf0, 0x2d, 0x0c, 0x6e, 0x55, 0xaa, 0x7d, 0xf1, 0x71, 0xb5, 0xd2, 0x62, 0xc5, 0x8d,
	0xd2, 0xac, 0x7a, 0x5e, 0x9d, 0xb4, 0x6e, 0x06, 0x49, 0x81, 0xc7, 0x09, 0xf4, 0x9d, 0x77, 0xb6,
	0xdd, 0x93, 0x1d, 0x91, 0xb5, 0x9f, 0x1c, 0xd2, 0xe8, 0x41, 0xc7, 0x39, 0xef, 0x94, 0xbe, 0x17,
	0x9a, 0x1d, 0x93, 0xad, 0x93, 0xe4, 0x38, 0xfc, 0x00, 0x27, 0x57, 0x22, 0x31, 0xa1, 0xe4, 0x26,
	0x54, 0x32, 0xb7, 0x7d, 0x8d, 0xcc, 0x27, 0x41, 0x99, 0x88, 0x17, 0x30, 0xca, 0x4d, 0xed, 0x83,
	0xd4, 0x69, 0x68, 0x14, 0x94, 0x68, 0xf8, 0x0e, 0x86, 0xb9, 0x99, 0x2c, 0x52, 0x83, 0x06, 0x86,
	0x41, 0x51, 0xc0, 0x53, 0x68, 0x2c, 0x84, 0xe4, 0xd2, 0xb0, 0x26, 0x59, 0x1a, 0x86, 0x10, 0x8e,
	0xa0, 0xbe, 0x50, 0xf7, 0x42, 0xb2, 0x17, 0x44, 0xd7, 0x8d, 0x05, 0xc8, 0xa0, 0x39, 0x53, 0xd2,
	0x88, 0x07, 0xc3, 0x5a, 0xc4, 0x37, 0x7d, 0x07, 0xad, 0xb2, 0x08, 0x23, 0xa1, 0x52, 0xc3, 0xc0,
	0x29, 0xc6, 0x41, 0x7c, 0x0d, 0x2d, 0xab, 0x24, 0x86, 0x47, 0x31, 0x6b, 0x93, 0xd6, 0x32, 0x5b,
	0xc2, 0xee, 0x73, 0xcd, 0x7f, 0x28, 0xcd, 0x3a, 0x6e, 0x9f, 0xc8, 0x02, 0x62, 0x43, 0xa9, 0x34,
	0xeb, 0x66, 0xac, 0x05, 0x88, 0x50, 0x5b, 0xa6, 0x61, 0xc0, 0x7a, 0x44, 0xd6, 0xd2, 0x34, 0x0c,
	0xf0, 0x0d, 0x74, 0x77, 0x47, 0x5f, 0x6c, 0x62, 0xc1, 0xfa, 0x24, 0x76, 0xfd, 0x3c, 0x89, 0xe7,
	0xd0, 0xce, 0x9a, 0x40, 0x9e, 0x01, 0x79, 0xda, 0xfe, 0x9e, 0x72, 0x27, 0x23, 0xc8, 0x86, 0xdb,
	0x93, 0x11, 0xb4, 0xca, 0x9c, 0x6f, 0xd6, 0x8a, 0x07, 0x0c, 0x9d, 0x12, 0x3b, 0xe8, 0x4d, 0x00,
	0x0f, 0xfb, 0xb5, 0x5c, 0x7e, 0xb9, 0xda, 0xa5, 0xac, 0xee, 0x53, 0x7a, 0x5f, 0x8b, 0xce, 0x3b,
	0x1e, 0x1a, 0xdb, 0x1b, 0x77, 0x0b, 0xae, 0x3d, 0xd9, 0x44, 0xe7, 0x57, 0x8e, 0xb3, 0x5f, 0xe2,
	0x1b, 0x5f, 0xa7, 0x22, 0xeb, 0x5e, 0xfd, 0xa7, 0x05, 0xde, 0xdf, 0x63, 0x78, 0x79, 0xb8, 0xe0,
	0x8d, 0x88, 0xd7, 0x9b, 0xe7, 0x7e, 0xff, 0x77, 0xfd, 0xde, 0xb6, 0xa1, 0x93, 0xeb, 0xec, 0x08,
	0xea, 0x74, 0x5d, 0xdb, 0x76, 0x6b, 0xba, 0xbb, 0x5c, 0xcf, 0x7a, 0x07, 0x3d, 0xbb, 0xf8, 0x7d,
	0x04, 0x83, 0x59, 0xe1, 0xe1, 0xc3, 0xcf, 0x80, 0xb7, 0x42, 0x06, 0x85, 0x07, 0x6e, 0x34, 0xb5,
	0x2f, 0xe1, 0xf4, 0x90, 0x1d, 0xb3, 0x32, 0xd6, 0x96, 0xd5, 0xab, 0xe0, 0x0c, 0xce, 0x1e, 0xaf,
	0xe3, 0xda, 0xf4, 0xaa, 0x6c, 0x8c, 0xa4, 0x71, 0xdb, 0x49, 0x9f, 0xa2, 0xd8, 0x6c, 0xbc, 0x8a,
	0x0d, 0x63, 0x1b, 0x5d, 0x08, 0x53, 0xba, 0xad, 0xf5, 0x8d, 0x4b, 0x63, 0x7a, 0x15, 0x9c, 0xc3,
	0xd9, 0xe3, 0x75, 0x5c, 0x98, 0xa7, 0x17, 0x7b, 0x3a, 0xa6, 0x57, 0xb9, 0x9c, 0xc2, 0x38, 0x54,
	0xce, 0x20, 0x1e, 0x78, 0x14, 0xaf, 0x45, 0x32, 0xdd, 0xbd, 0x0d, 0x97, 0xbd, 0xdd, 0x67, 0x9d,
	0xdb, 0x5f, 0xc6, 0xbc, 0xfa, 0xbd, 0x41, 0xff, 0x8e, 0xf7, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xf5, 0xcf, 0x10, 0xb0, 0x6a, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConnectorCommandClient is the client API for ConnectorCommand service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConnectorCommandClient interface {
	SendCommandMessage(ctx context.Context, in *CommandMessage, opts ...grpc.CallOption) (*CommandMessageUUID, error)
	SendCommandMessageReply(ctx context.Context, in *CommandMessageReply, opts ...grpc.CallOption) (*Empty, error)
	WaitCommandMessage(ctx context.Context, in *CommandMessageWait, opts ...grpc.CallOption) (*CommandMessage, error)
	WaitCommandMessageReply(ctx context.Context, in *CommandMessageWait, opts ...grpc.CallOption) (*CommandMessageReply, error)
}

type connectorCommandClient struct {
	cc *grpc.ClientConn
}

func NewConnectorCommandClient(cc *grpc.ClientConn) ConnectorCommandClient {
	return &connectorCommandClient{cc}
}

func (c *connectorCommandClient) SendCommandMessage(ctx context.Context, in *CommandMessage, opts ...grpc.CallOption) (*CommandMessageUUID, error) {
	out := new(CommandMessageUUID)
	err := c.cc.Invoke(ctx, "/grpc.ConnectorCommand/SendCommandMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorCommandClient) SendCommandMessageReply(ctx context.Context, in *CommandMessageReply, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/grpc.ConnectorCommand/SendCommandMessageReply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorCommandClient) WaitCommandMessage(ctx context.Context, in *CommandMessageWait, opts ...grpc.CallOption) (*CommandMessage, error) {
	out := new(CommandMessage)
	err := c.cc.Invoke(ctx, "/grpc.ConnectorCommand/WaitCommandMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorCommandClient) WaitCommandMessageReply(ctx context.Context, in *CommandMessageWait, opts ...grpc.CallOption) (*CommandMessageReply, error) {
	out := new(CommandMessageReply)
	err := c.cc.Invoke(ctx, "/grpc.ConnectorCommand/WaitCommandMessageReply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnectorCommandServer is the server API for ConnectorCommand service.
type ConnectorCommandServer interface {
	SendCommandMessage(context.Context, *CommandMessage) (*CommandMessageUUID, error)
	SendCommandMessageReply(context.Context, *CommandMessageReply) (*Empty, error)
	WaitCommandMessage(context.Context, *CommandMessageWait) (*CommandMessage, error)
	WaitCommandMessageReply(context.Context, *CommandMessageWait) (*CommandMessageReply, error)
}

// UnimplementedConnectorCommandServer can be embedded to have forward compatible implementations.
type UnimplementedConnectorCommandServer struct {
}

func (*UnimplementedConnectorCommandServer) SendCommandMessage(ctx context.Context, req *CommandMessage) (*CommandMessageUUID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCommandMessage not implemented")
}
func (*UnimplementedConnectorCommandServer) SendCommandMessageReply(ctx context.Context, req *CommandMessageReply) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCommandMessageReply not implemented")
}
func (*UnimplementedConnectorCommandServer) WaitCommandMessage(ctx context.Context, req *CommandMessageWait) (*CommandMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitCommandMessage not implemented")
}
func (*UnimplementedConnectorCommandServer) WaitCommandMessageReply(ctx context.Context, req *CommandMessageWait) (*CommandMessageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitCommandMessageReply not implemented")
}

func RegisterConnectorCommandServer(s *grpc.Server, srv ConnectorCommandServer) {
	s.RegisterService(&_ConnectorCommand_serviceDesc, srv)
}

func _ConnectorCommand_SendCommandMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorCommandServer).SendCommandMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.ConnectorCommand/SendCommandMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorCommandServer).SendCommandMessage(ctx, req.(*CommandMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorCommand_SendCommandMessageReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandMessageReply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorCommandServer).SendCommandMessageReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.ConnectorCommand/SendCommandMessageReply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorCommandServer).SendCommandMessageReply(ctx, req.(*CommandMessageReply))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorCommand_WaitCommandMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandMessageWait)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorCommandServer).WaitCommandMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.ConnectorCommand/WaitCommandMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorCommandServer).WaitCommandMessage(ctx, req.(*CommandMessageWait))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorCommand_WaitCommandMessageReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandMessageWait)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorCommandServer).WaitCommandMessageReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.ConnectorCommand/WaitCommandMessageReply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorCommandServer).WaitCommandMessageReply(ctx, req.(*CommandMessageWait))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConnectorCommand_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.ConnectorCommand",
	HandlerType: (*ConnectorCommandServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendCommandMessage",
			Handler:    _ConnectorCommand_SendCommandMessage_Handler,
		},
		{
			MethodName: "SendCommandMessageReply",
			Handler:    _ConnectorCommand_SendCommandMessageReply_Handler,
		},
		{
			MethodName: "WaitCommandMessage",
			Handler:    _ConnectorCommand_WaitCommandMessage_Handler,
		},
		{
			MethodName: "WaitCommandMessageReply",
			Handler:    _ConnectorCommand_WaitCommandMessageReply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "connectorCommand.proto",
}
