// Code generated by protoc-gen-go. DO NOT EDIT.
// source: connector.proto

/*
Package connector is a generated protocol buffer package.

It is generated from these files:
	connector.proto

It has these top-level messages:
	CommandMessage
	CommandMessageRequest
	CommandMessageUUID
	CommandMessageReply
	EventMessage
	EventMessageRequest
	Empty
*/
package connector

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CommandMessage struct {
	Target  string `protobuf:"bytes,1,opt,name=target" json:"target,omitempty"`
	Command string `protobuf:"bytes,2,opt,name=command" json:"command,omitempty"`
	Payload string `protobuf:"bytes,3,opt,name=payload" json:"payload,omitempty"`
}

func (m *CommandMessage) Reset()                    { *m = CommandMessage{} }
func (m *CommandMessage) String() string            { return proto.CompactTextString(m) }
func (*CommandMessage) ProtoMessage()               {}
func (*CommandMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CommandMessage) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *CommandMessage) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *CommandMessage) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type CommandMessageRequest struct {
	Command string `protobuf:"bytes,1,opt,name=command" json:"command,omitempty"`
}

func (m *CommandMessageRequest) Reset()                    { *m = CommandMessageRequest{} }
func (m *CommandMessageRequest) String() string            { return proto.CompactTextString(m) }
func (*CommandMessageRequest) ProtoMessage()               {}
func (*CommandMessageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CommandMessageRequest) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

type CommandMessageUUID struct {
	Uuid string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
}

func (m *CommandMessageUUID) Reset()                    { *m = CommandMessageUUID{} }
func (m *CommandMessageUUID) String() string            { return proto.CompactTextString(m) }
func (*CommandMessageUUID) ProtoMessage()               {}
func (*CommandMessageUUID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CommandMessageUUID) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type CommandMessageReply struct {
	Uuid    string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	State   string `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
	Payload string `protobuf:"bytes,3,opt,name=payload" json:"payload,omitempty"`
}

func (m *CommandMessageReply) Reset()                    { *m = CommandMessageReply{} }
func (m *CommandMessageReply) String() string            { return proto.CompactTextString(m) }
func (*CommandMessageReply) ProtoMessage()               {}
func (*CommandMessageReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CommandMessageReply) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *CommandMessageReply) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *CommandMessageReply) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type EventMessage struct {
	Topic   string `protobuf:"bytes,1,opt,name=topic" json:"topic,omitempty"`
	Event   string `protobuf:"bytes,2,opt,name=event" json:"event,omitempty"`
	Payload string `protobuf:"bytes,3,opt,name=payload" json:"payload,omitempty"`
}

func (m *EventMessage) Reset()                    { *m = EventMessage{} }
func (m *EventMessage) String() string            { return proto.CompactTextString(m) }
func (*EventMessage) ProtoMessage()               {}
func (*EventMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *EventMessage) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *EventMessage) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *EventMessage) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type EventMessageRequest struct {
	Topic string `protobuf:"bytes,1,opt,name=topic" json:"topic,omitempty"`
	Event string `protobuf:"bytes,2,opt,name=event" json:"event,omitempty"`
}

func (m *EventMessageRequest) Reset()                    { *m = EventMessageRequest{} }
func (m *EventMessageRequest) String() string            { return proto.CompactTextString(m) }
func (*EventMessageRequest) ProtoMessage()               {}
func (*EventMessageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *EventMessageRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *EventMessageRequest) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func init() {
	proto.RegisterType((*CommandMessage)(nil), "connector.CommandMessage")
	proto.RegisterType((*CommandMessageRequest)(nil), "connector.CommandMessageRequest")
	proto.RegisterType((*CommandMessageUUID)(nil), "connector.CommandMessageUUID")
	proto.RegisterType((*CommandMessageReply)(nil), "connector.CommandMessageReply")
	proto.RegisterType((*EventMessage)(nil), "connector.EventMessage")
	proto.RegisterType((*EventMessageRequest)(nil), "connector.EventMessageRequest")
	proto.RegisterType((*Empty)(nil), "connector.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Connector service

type ConnectorClient interface {
	// Sends a greeting
	SendCommandMessage(ctx context.Context, in *CommandMessage, opts ...grpc.CallOption) (*CommandMessageUUID, error)
	SendCommandMessageReply(ctx context.Context, in *CommandMessageReply, opts ...grpc.CallOption) (*Empty, error)
	SendEventMessage(ctx context.Context, in *EventMessage, opts ...grpc.CallOption) (*Empty, error)
	WaitCommandMessage(ctx context.Context, in *CommandMessageRequest, opts ...grpc.CallOption) (*CommandMessage, error)
	WaitCommandMessageReply(ctx context.Context, in *CommandMessageUUID, opts ...grpc.CallOption) (*CommandMessageReply, error)
	WaitEventMessage(ctx context.Context, in *EventMessageRequest, opts ...grpc.CallOption) (*EventMessage, error)
}

type connectorClient struct {
	cc *grpc.ClientConn
}

func NewConnectorClient(cc *grpc.ClientConn) ConnectorClient {
	return &connectorClient{cc}
}

func (c *connectorClient) SendCommandMessage(ctx context.Context, in *CommandMessage, opts ...grpc.CallOption) (*CommandMessageUUID, error) {
	out := new(CommandMessageUUID)
	err := grpc.Invoke(ctx, "/connector.Connector/SendCommandMessage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorClient) SendCommandMessageReply(ctx context.Context, in *CommandMessageReply, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/connector.Connector/SendCommandMessageReply", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorClient) SendEventMessage(ctx context.Context, in *EventMessage, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/connector.Connector/SendEventMessage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorClient) WaitCommandMessage(ctx context.Context, in *CommandMessageRequest, opts ...grpc.CallOption) (*CommandMessage, error) {
	out := new(CommandMessage)
	err := grpc.Invoke(ctx, "/connector.Connector/WaitCommandMessage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorClient) WaitCommandMessageReply(ctx context.Context, in *CommandMessageUUID, opts ...grpc.CallOption) (*CommandMessageReply, error) {
	out := new(CommandMessageReply)
	err := grpc.Invoke(ctx, "/connector.Connector/WaitCommandMessageReply", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorClient) WaitEventMessage(ctx context.Context, in *EventMessageRequest, opts ...grpc.CallOption) (*EventMessage, error) {
	out := new(EventMessage)
	err := grpc.Invoke(ctx, "/connector.Connector/WaitEventMessage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Connector service

type ConnectorServer interface {
	// Sends a greeting
	SendCommandMessage(context.Context, *CommandMessage) (*CommandMessageUUID, error)
	SendCommandMessageReply(context.Context, *CommandMessageReply) (*Empty, error)
	SendEventMessage(context.Context, *EventMessage) (*Empty, error)
	WaitCommandMessage(context.Context, *CommandMessageRequest) (*CommandMessage, error)
	WaitCommandMessageReply(context.Context, *CommandMessageUUID) (*CommandMessageReply, error)
	WaitEventMessage(context.Context, *EventMessageRequest) (*EventMessage, error)
}

func RegisterConnectorServer(s *grpc.Server, srv ConnectorServer) {
	s.RegisterService(&_Connector_serviceDesc, srv)
}

func _Connector_SendCommandMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorServer).SendCommandMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connector.Connector/SendCommandMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorServer).SendCommandMessage(ctx, req.(*CommandMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Connector_SendCommandMessageReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandMessageReply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorServer).SendCommandMessageReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connector.Connector/SendCommandMessageReply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorServer).SendCommandMessageReply(ctx, req.(*CommandMessageReply))
	}
	return interceptor(ctx, in, info, handler)
}

func _Connector_SendEventMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorServer).SendEventMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connector.Connector/SendEventMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorServer).SendEventMessage(ctx, req.(*EventMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Connector_WaitCommandMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorServer).WaitCommandMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connector.Connector/WaitCommandMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorServer).WaitCommandMessage(ctx, req.(*CommandMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Connector_WaitCommandMessageReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandMessageUUID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorServer).WaitCommandMessageReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connector.Connector/WaitCommandMessageReply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorServer).WaitCommandMessageReply(ctx, req.(*CommandMessageUUID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Connector_WaitEventMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorServer).WaitEventMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connector.Connector/WaitEventMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorServer).WaitEventMessage(ctx, req.(*EventMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Connector_serviceDesc = grpc.ServiceDesc{
	ServiceName: "connector.Connector",
	HandlerType: (*ConnectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendCommandMessage",
			Handler:    _Connector_SendCommandMessage_Handler,
		},
		{
			MethodName: "SendCommandMessageReply",
			Handler:    _Connector_SendCommandMessageReply_Handler,
		},
		{
			MethodName: "SendEventMessage",
			Handler:    _Connector_SendEventMessage_Handler,
		},
		{
			MethodName: "WaitCommandMessage",
			Handler:    _Connector_WaitCommandMessage_Handler,
		},
		{
			MethodName: "WaitCommandMessageReply",
			Handler:    _Connector_WaitCommandMessageReply_Handler,
		},
		{
			MethodName: "WaitEventMessage",
			Handler:    _Connector_WaitEventMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "connector.proto",
}

func init() { proto.RegisterFile("connector.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x51, 0x6b, 0xea, 0x30,
	0x14, 0xc7, 0xdb, 0xeb, 0x55, 0xf1, 0x70, 0xf1, 0x4a, 0x74, 0xb3, 0x2b, 0x4c, 0x24, 0x4f, 0x3e,
	0x15, 0xb6, 0x7d, 0x80, 0x31, 0x9d, 0x0f, 0x7b, 0x10, 0x44, 0x27, 0x63, 0x63, 0x2f, 0x59, 0x0d,
	0x52, 0xb0, 0x4d, 0xd6, 0xc6, 0x31, 0x3f, 0xf4, 0xbe, 0xc3, 0x48, 0xda, 0x68, 0xa3, 0xb6, 0x63,
	0x6f, 0x3d, 0xf9, 0xff, 0xf3, 0xe3, 0x9c, 0xff, 0x69, 0xe0, 0xbf, 0xcf, 0xa2, 0x88, 0xfa, 0x82,
	0xc5, 0x1e, 0x8f, 0x99, 0x60, 0xa8, 0xb1, 0x3b, 0xc0, 0xaf, 0xd0, 0x1c, 0xb1, 0x30, 0x24, 0xd1,
	0x72, 0x42, 0x93, 0x84, 0xac, 0x28, 0x3a, 0x87, 0x9a, 0x20, 0xf1, 0x8a, 0x0a, 0xc7, 0xee, 0xdb,
	0x83, 0xc6, 0x2c, 0xab, 0x90, 0x03, 0x75, 0x3f, 0x75, 0x3a, 0x7f, 0x94, 0xa0, 0x4b, 0xa9, 0x70,
	0xb2, 0x5d, 0x33, 0xb2, 0x74, 0x2a, 0xa9, 0x92, 0x95, 0xf8, 0x0a, 0xce, 0x4c, 0xfa, 0x8c, 0xbe,
	0x6f, 0x68, 0x62, 0xc0, 0x6c, 0x03, 0x86, 0x07, 0x80, 0xcc, 0x2b, 0x8b, 0xc5, 0xc3, 0x3d, 0x42,
	0xf0, 0x77, 0xb3, 0x09, 0xb4, 0x59, 0x7d, 0xe3, 0x67, 0x68, 0x1f, 0xc2, 0xf9, 0x7a, 0x7b, 0xca,
	0x8a, 0x3a, 0x50, 0x4d, 0x04, 0x11, 0x34, 0xeb, 0x3c, 0x2d, 0x4a, 0xfa, 0x7e, 0x84, 0x7f, 0xe3,
	0x0f, 0x1a, 0x09, 0x9d, 0x49, 0x07, 0xaa, 0x82, 0xf1, 0xc0, 0xcf, 0xa0, 0x69, 0x21, 0x4f, 0xa9,
	0x74, 0x69, 0xaa, 0x2a, 0x4a, 0xa8, 0x77, 0xd0, 0xce, 0x53, 0x75, 0x16, 0xbf, 0x80, 0xe3, 0x3a,
	0x54, 0xc7, 0x21, 0x17, 0xdb, 0xeb, 0xaf, 0x0a, 0x34, 0x46, 0x7a, 0x8b, 0x68, 0x0a, 0x68, 0x4e,
	0xa3, 0xe5, 0xc1, 0x26, 0x2f, 0xbc, 0xfd, 0xe2, 0x4d, 0xc9, 0xbd, 0x2c, 0x94, 0x64, 0xdc, 0xd8,
	0x42, 0x13, 0xe8, 0x1e, 0x13, 0xd3, 0x80, 0x7b, 0x85, 0x77, 0x95, 0xee, 0xb6, 0x72, 0xba, 0x6a,
	0x16, 0x5b, 0xe8, 0x16, 0x5a, 0x12, 0x67, 0x84, 0xda, 0xcd, 0xfb, 0x72, 0xc2, 0x49, 0xc0, 0x1c,
	0xd0, 0x13, 0x09, 0xc4, 0xc1, 0x84, 0xfd, 0x92, 0x56, 0x54, 0xb8, 0x6e, 0x71, 0x06, 0xd8, 0x42,
	0x2f, 0xd0, 0x3d, 0x86, 0xa6, 0x43, 0x96, 0x07, 0xe4, 0xfe, 0x90, 0x81, 0x0a, 0xb0, 0x25, 0xd9,
	0xc6, 0xc4, 0xbd, 0x82, 0x89, 0x75, 0xb3, 0x45, 0x89, 0x60, 0x6b, 0xe8, 0x81, 0x1b, 0x30, 0x6f,
	0x15, 0x73, 0xdf, 0xa3, 0x9f, 0x24, 0xe4, 0x6b, 0x9a, 0xec, 0xcd, 0xc3, 0xe6, 0xee, 0x57, 0x98,
	0xca, 0x07, 0x3e, 0xb5, 0xdf, 0x6a, 0xea, 0xa5, 0xdf, 0x7c, 0x07, 0x00, 0x00, 0xff, 0xff, 0x06,
	0x68, 0x89, 0xbb, 0xfc, 0x03, 0x00, 0x00,
}
