// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connectorCommand.proto

package com.ditrit.gandalf.java.grpc;

public interface CommandMessageWaitOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.CommandMessageWait)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string WorkerSource = 1;</code>
   */
  java.lang.String getWorkerSource();
  /**
   * <code>optional string WorkerSource = 1;</code>
   */
  com.google.protobuf.ByteString
      getWorkerSourceBytes();

  /**
   * <code>optional string Value = 2;</code>
   */
  java.lang.String getValue();
  /**
   * <code>optional string Value = 2;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();

  /**
   * <code>optional string IteratorId = 3;</code>
   */
  java.lang.String getIteratorId();
  /**
   * <code>optional string IteratorId = 3;</code>
   */
  com.google.protobuf.ByteString
      getIteratorIdBytes();
}
