// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connectorCommand.proto

package com.ditrit.gandalf.java.grpc;

/**
 * Protobuf type {@code grpc.CommandMessage}
 */
public  final class CommandMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.CommandMessage)
    CommandMessageOrBuilder {
  // Use CommandMessage.newBuilder() to construct.
  private CommandMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CommandMessage() {
    sourceAggregator_ = "";
    sourceConnector_ = "";
    sourceWorker_ = "";
    destinationAggregator_ = "";
    destinationConnector_ = "";
    destinationWorker_ = "";
    tenant_ = "";
    token_ = "";
    context_ = "";
    timeout_ = "";
    timestamp_ = "";
    major_ = "";
    minor_ = "";
    uUID_ = "";
    connectorType_ = "";
    commandType_ = "";
    command_ = "";
    payload_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private CommandMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            sourceAggregator_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            sourceConnector_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            sourceWorker_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            destinationAggregator_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            destinationConnector_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            destinationWorker_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            tenant_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            token_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            context_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            timeout_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            timestamp_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            major_ = s;
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            minor_ = s;
            break;
          }
          case 114: {
            java.lang.String s = input.readStringRequireUtf8();

            uUID_ = s;
            break;
          }
          case 122: {
            java.lang.String s = input.readStringRequireUtf8();

            connectorType_ = s;
            break;
          }
          case 130: {
            java.lang.String s = input.readStringRequireUtf8();

            commandType_ = s;
            break;
          }
          case 138: {
            java.lang.String s = input.readStringRequireUtf8();

            command_ = s;
            break;
          }
          case 146: {
            java.lang.String s = input.readStringRequireUtf8();

            payload_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ditrit.gandalf.java.grpc.ConnectorCommandProto.internal_static_grpc_CommandMessage_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ditrit.gandalf.java.grpc.ConnectorCommandProto.internal_static_grpc_CommandMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ditrit.gandalf.java.grpc.CommandMessage.class, com.ditrit.gandalf.java.grpc.CommandMessage.Builder.class);
  }

  public static final int SOURCEAGGREGATOR_FIELD_NUMBER = 1;
  private volatile java.lang.Object sourceAggregator_;
  /**
   * <code>optional string SourceAggregator = 1;</code>
   */
  public java.lang.String getSourceAggregator() {
    java.lang.Object ref = sourceAggregator_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceAggregator_ = s;
      return s;
    }
  }
  /**
   * <code>optional string SourceAggregator = 1;</code>
   */
  public com.google.protobuf.ByteString
      getSourceAggregatorBytes() {
    java.lang.Object ref = sourceAggregator_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceAggregator_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCECONNECTOR_FIELD_NUMBER = 2;
  private volatile java.lang.Object sourceConnector_;
  /**
   * <code>optional string SourceConnector = 2;</code>
   */
  public java.lang.String getSourceConnector() {
    java.lang.Object ref = sourceConnector_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceConnector_ = s;
      return s;
    }
  }
  /**
   * <code>optional string SourceConnector = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSourceConnectorBytes() {
    java.lang.Object ref = sourceConnector_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceConnector_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCEWORKER_FIELD_NUMBER = 3;
  private volatile java.lang.Object sourceWorker_;
  /**
   * <code>optional string SourceWorker = 3;</code>
   */
  public java.lang.String getSourceWorker() {
    java.lang.Object ref = sourceWorker_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceWorker_ = s;
      return s;
    }
  }
  /**
   * <code>optional string SourceWorker = 3;</code>
   */
  public com.google.protobuf.ByteString
      getSourceWorkerBytes() {
    java.lang.Object ref = sourceWorker_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceWorker_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESTINATIONAGGREGATOR_FIELD_NUMBER = 4;
  private volatile java.lang.Object destinationAggregator_;
  /**
   * <code>optional string DestinationAggregator = 4;</code>
   */
  public java.lang.String getDestinationAggregator() {
    java.lang.Object ref = destinationAggregator_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      destinationAggregator_ = s;
      return s;
    }
  }
  /**
   * <code>optional string DestinationAggregator = 4;</code>
   */
  public com.google.protobuf.ByteString
      getDestinationAggregatorBytes() {
    java.lang.Object ref = destinationAggregator_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      destinationAggregator_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESTINATIONCONNECTOR_FIELD_NUMBER = 5;
  private volatile java.lang.Object destinationConnector_;
  /**
   * <code>optional string DestinationConnector = 5;</code>
   */
  public java.lang.String getDestinationConnector() {
    java.lang.Object ref = destinationConnector_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      destinationConnector_ = s;
      return s;
    }
  }
  /**
   * <code>optional string DestinationConnector = 5;</code>
   */
  public com.google.protobuf.ByteString
      getDestinationConnectorBytes() {
    java.lang.Object ref = destinationConnector_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      destinationConnector_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESTINATIONWORKER_FIELD_NUMBER = 6;
  private volatile java.lang.Object destinationWorker_;
  /**
   * <code>optional string DestinationWorker = 6;</code>
   */
  public java.lang.String getDestinationWorker() {
    java.lang.Object ref = destinationWorker_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      destinationWorker_ = s;
      return s;
    }
  }
  /**
   * <code>optional string DestinationWorker = 6;</code>
   */
  public com.google.protobuf.ByteString
      getDestinationWorkerBytes() {
    java.lang.Object ref = destinationWorker_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      destinationWorker_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TENANT_FIELD_NUMBER = 7;
  private volatile java.lang.Object tenant_;
  /**
   * <code>optional string Tenant = 7;</code>
   */
  public java.lang.String getTenant() {
    java.lang.Object ref = tenant_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tenant_ = s;
      return s;
    }
  }
  /**
   * <code>optional string Tenant = 7;</code>
   */
  public com.google.protobuf.ByteString
      getTenantBytes() {
    java.lang.Object ref = tenant_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tenant_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOKEN_FIELD_NUMBER = 8;
  private volatile java.lang.Object token_;
  /**
   * <code>optional string Token = 8;</code>
   */
  public java.lang.String getToken() {
    java.lang.Object ref = token_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      token_ = s;
      return s;
    }
  }
  /**
   * <code>optional string Token = 8;</code>
   */
  public com.google.protobuf.ByteString
      getTokenBytes() {
    java.lang.Object ref = token_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      token_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTEXT_FIELD_NUMBER = 9;
  private volatile java.lang.Object context_;
  /**
   * <code>optional string Context = 9;</code>
   */
  public java.lang.String getContext() {
    java.lang.Object ref = context_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      context_ = s;
      return s;
    }
  }
  /**
   * <code>optional string Context = 9;</code>
   */
  public com.google.protobuf.ByteString
      getContextBytes() {
    java.lang.Object ref = context_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      context_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMEOUT_FIELD_NUMBER = 10;
  private volatile java.lang.Object timeout_;
  /**
   * <code>optional string Timeout = 10;</code>
   */
  public java.lang.String getTimeout() {
    java.lang.Object ref = timeout_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timeout_ = s;
      return s;
    }
  }
  /**
   * <code>optional string Timeout = 10;</code>
   */
  public com.google.protobuf.ByteString
      getTimeoutBytes() {
    java.lang.Object ref = timeout_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timeout_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 11;
  private volatile java.lang.Object timestamp_;
  /**
   * <code>optional string Timestamp = 11;</code>
   */
  public java.lang.String getTimestamp() {
    java.lang.Object ref = timestamp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timestamp_ = s;
      return s;
    }
  }
  /**
   * <code>optional string Timestamp = 11;</code>
   */
  public com.google.protobuf.ByteString
      getTimestampBytes() {
    java.lang.Object ref = timestamp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timestamp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MAJOR_FIELD_NUMBER = 12;
  private volatile java.lang.Object major_;
  /**
   * <code>optional string Major = 12;</code>
   */
  public java.lang.String getMajor() {
    java.lang.Object ref = major_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      major_ = s;
      return s;
    }
  }
  /**
   * <code>optional string Major = 12;</code>
   */
  public com.google.protobuf.ByteString
      getMajorBytes() {
    java.lang.Object ref = major_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      major_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MINOR_FIELD_NUMBER = 13;
  private volatile java.lang.Object minor_;
  /**
   * <code>optional string Minor = 13;</code>
   */
  public java.lang.String getMinor() {
    java.lang.Object ref = minor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      minor_ = s;
      return s;
    }
  }
  /**
   * <code>optional string Minor = 13;</code>
   */
  public com.google.protobuf.ByteString
      getMinorBytes() {
    java.lang.Object ref = minor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      minor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UUID_FIELD_NUMBER = 14;
  private volatile java.lang.Object uUID_;
  /**
   * <code>optional string UUID = 14;</code>
   */
  public java.lang.String getUUID() {
    java.lang.Object ref = uUID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      uUID_ = s;
      return s;
    }
  }
  /**
   * <code>optional string UUID = 14;</code>
   */
  public com.google.protobuf.ByteString
      getUUIDBytes() {
    java.lang.Object ref = uUID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uUID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONNECTORTYPE_FIELD_NUMBER = 15;
  private volatile java.lang.Object connectorType_;
  /**
   * <code>optional string ConnectorType = 15;</code>
   */
  public java.lang.String getConnectorType() {
    java.lang.Object ref = connectorType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      connectorType_ = s;
      return s;
    }
  }
  /**
   * <code>optional string ConnectorType = 15;</code>
   */
  public com.google.protobuf.ByteString
      getConnectorTypeBytes() {
    java.lang.Object ref = connectorType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      connectorType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMMANDTYPE_FIELD_NUMBER = 16;
  private volatile java.lang.Object commandType_;
  /**
   * <code>optional string CommandType = 16;</code>
   */
  public java.lang.String getCommandType() {
    java.lang.Object ref = commandType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      commandType_ = s;
      return s;
    }
  }
  /**
   * <code>optional string CommandType = 16;</code>
   */
  public com.google.protobuf.ByteString
      getCommandTypeBytes() {
    java.lang.Object ref = commandType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      commandType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMMAND_FIELD_NUMBER = 17;
  private volatile java.lang.Object command_;
  /**
   * <code>optional string Command = 17;</code>
   */
  public java.lang.String getCommand() {
    java.lang.Object ref = command_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      command_ = s;
      return s;
    }
  }
  /**
   * <code>optional string Command = 17;</code>
   */
  public com.google.protobuf.ByteString
      getCommandBytes() {
    java.lang.Object ref = command_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      command_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAYLOAD_FIELD_NUMBER = 18;
  private volatile java.lang.Object payload_;
  /**
   * <code>optional string Payload = 18;</code>
   */
  public java.lang.String getPayload() {
    java.lang.Object ref = payload_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      payload_ = s;
      return s;
    }
  }
  /**
   * <code>optional string Payload = 18;</code>
   */
  public com.google.protobuf.ByteString
      getPayloadBytes() {
    java.lang.Object ref = payload_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      payload_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSourceAggregatorBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sourceAggregator_);
    }
    if (!getSourceConnectorBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sourceConnector_);
    }
    if (!getSourceWorkerBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sourceWorker_);
    }
    if (!getDestinationAggregatorBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, destinationAggregator_);
    }
    if (!getDestinationConnectorBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, destinationConnector_);
    }
    if (!getDestinationWorkerBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, destinationWorker_);
    }
    if (!getTenantBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, tenant_);
    }
    if (!getTokenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, token_);
    }
    if (!getContextBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, context_);
    }
    if (!getTimeoutBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, timeout_);
    }
    if (!getTimestampBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, timestamp_);
    }
    if (!getMajorBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, major_);
    }
    if (!getMinorBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, minor_);
    }
    if (!getUUIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, uUID_);
    }
    if (!getConnectorTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, connectorType_);
    }
    if (!getCommandTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 16, commandType_);
    }
    if (!getCommandBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 17, command_);
    }
    if (!getPayloadBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 18, payload_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSourceAggregatorBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sourceAggregator_);
    }
    if (!getSourceConnectorBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sourceConnector_);
    }
    if (!getSourceWorkerBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sourceWorker_);
    }
    if (!getDestinationAggregatorBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, destinationAggregator_);
    }
    if (!getDestinationConnectorBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, destinationConnector_);
    }
    if (!getDestinationWorkerBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, destinationWorker_);
    }
    if (!getTenantBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, tenant_);
    }
    if (!getTokenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, token_);
    }
    if (!getContextBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, context_);
    }
    if (!getTimeoutBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, timeout_);
    }
    if (!getTimestampBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, timestamp_);
    }
    if (!getMajorBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, major_);
    }
    if (!getMinorBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, minor_);
    }
    if (!getUUIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, uUID_);
    }
    if (!getConnectorTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, connectorType_);
    }
    if (!getCommandTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, commandType_);
    }
    if (!getCommandBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(17, command_);
    }
    if (!getPayloadBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(18, payload_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ditrit.gandalf.java.grpc.CommandMessage)) {
      return super.equals(obj);
    }
    com.ditrit.gandalf.java.grpc.CommandMessage other = (com.ditrit.gandalf.java.grpc.CommandMessage) obj;

    boolean result = true;
    result = result && getSourceAggregator()
        .equals(other.getSourceAggregator());
    result = result && getSourceConnector()
        .equals(other.getSourceConnector());
    result = result && getSourceWorker()
        .equals(other.getSourceWorker());
    result = result && getDestinationAggregator()
        .equals(other.getDestinationAggregator());
    result = result && getDestinationConnector()
        .equals(other.getDestinationConnector());
    result = result && getDestinationWorker()
        .equals(other.getDestinationWorker());
    result = result && getTenant()
        .equals(other.getTenant());
    result = result && getToken()
        .equals(other.getToken());
    result = result && getContext()
        .equals(other.getContext());
    result = result && getTimeout()
        .equals(other.getTimeout());
    result = result && getTimestamp()
        .equals(other.getTimestamp());
    result = result && getMajor()
        .equals(other.getMajor());
    result = result && getMinor()
        .equals(other.getMinor());
    result = result && getUUID()
        .equals(other.getUUID());
    result = result && getConnectorType()
        .equals(other.getConnectorType());
    result = result && getCommandType()
        .equals(other.getCommandType());
    result = result && getCommand()
        .equals(other.getCommand());
    result = result && getPayload()
        .equals(other.getPayload());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + SOURCEAGGREGATOR_FIELD_NUMBER;
    hash = (53 * hash) + getSourceAggregator().hashCode();
    hash = (37 * hash) + SOURCECONNECTOR_FIELD_NUMBER;
    hash = (53 * hash) + getSourceConnector().hashCode();
    hash = (37 * hash) + SOURCEWORKER_FIELD_NUMBER;
    hash = (53 * hash) + getSourceWorker().hashCode();
    hash = (37 * hash) + DESTINATIONAGGREGATOR_FIELD_NUMBER;
    hash = (53 * hash) + getDestinationAggregator().hashCode();
    hash = (37 * hash) + DESTINATIONCONNECTOR_FIELD_NUMBER;
    hash = (53 * hash) + getDestinationConnector().hashCode();
    hash = (37 * hash) + DESTINATIONWORKER_FIELD_NUMBER;
    hash = (53 * hash) + getDestinationWorker().hashCode();
    hash = (37 * hash) + TENANT_FIELD_NUMBER;
    hash = (53 * hash) + getTenant().hashCode();
    hash = (37 * hash) + TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getToken().hashCode();
    hash = (37 * hash) + CONTEXT_FIELD_NUMBER;
    hash = (53 * hash) + getContext().hashCode();
    hash = (37 * hash) + TIMEOUT_FIELD_NUMBER;
    hash = (53 * hash) + getTimeout().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + getTimestamp().hashCode();
    hash = (37 * hash) + MAJOR_FIELD_NUMBER;
    hash = (53 * hash) + getMajor().hashCode();
    hash = (37 * hash) + MINOR_FIELD_NUMBER;
    hash = (53 * hash) + getMinor().hashCode();
    hash = (37 * hash) + UUID_FIELD_NUMBER;
    hash = (53 * hash) + getUUID().hashCode();
    hash = (37 * hash) + CONNECTORTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getConnectorType().hashCode();
    hash = (37 * hash) + COMMANDTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getCommandType().hashCode();
    hash = (37 * hash) + COMMAND_FIELD_NUMBER;
    hash = (53 * hash) + getCommand().hashCode();
    hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
    hash = (53 * hash) + getPayload().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ditrit.gandalf.java.grpc.CommandMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ditrit.gandalf.java.grpc.CommandMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ditrit.gandalf.java.grpc.CommandMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ditrit.gandalf.java.grpc.CommandMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ditrit.gandalf.java.grpc.CommandMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ditrit.gandalf.java.grpc.CommandMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ditrit.gandalf.java.grpc.CommandMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ditrit.gandalf.java.grpc.CommandMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ditrit.gandalf.java.grpc.CommandMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ditrit.gandalf.java.grpc.CommandMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ditrit.gandalf.java.grpc.CommandMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpc.CommandMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.CommandMessage)
      com.ditrit.gandalf.java.grpc.CommandMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ditrit.gandalf.java.grpc.ConnectorCommandProto.internal_static_grpc_CommandMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ditrit.gandalf.java.grpc.ConnectorCommandProto.internal_static_grpc_CommandMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ditrit.gandalf.java.grpc.CommandMessage.class, com.ditrit.gandalf.java.grpc.CommandMessage.Builder.class);
    }

    // Construct using com.ditrit.gandalf.java.grpc.CommandMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      sourceAggregator_ = "";

      sourceConnector_ = "";

      sourceWorker_ = "";

      destinationAggregator_ = "";

      destinationConnector_ = "";

      destinationWorker_ = "";

      tenant_ = "";

      token_ = "";

      context_ = "";

      timeout_ = "";

      timestamp_ = "";

      major_ = "";

      minor_ = "";

      uUID_ = "";

      connectorType_ = "";

      commandType_ = "";

      command_ = "";

      payload_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ditrit.gandalf.java.grpc.ConnectorCommandProto.internal_static_grpc_CommandMessage_descriptor;
    }

    public com.ditrit.gandalf.java.grpc.CommandMessage getDefaultInstanceForType() {
      return com.ditrit.gandalf.java.grpc.CommandMessage.getDefaultInstance();
    }

    public com.ditrit.gandalf.java.grpc.CommandMessage build() {
      com.ditrit.gandalf.java.grpc.CommandMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.ditrit.gandalf.java.grpc.CommandMessage buildPartial() {
      com.ditrit.gandalf.java.grpc.CommandMessage result = new com.ditrit.gandalf.java.grpc.CommandMessage(this);
      result.sourceAggregator_ = sourceAggregator_;
      result.sourceConnector_ = sourceConnector_;
      result.sourceWorker_ = sourceWorker_;
      result.destinationAggregator_ = destinationAggregator_;
      result.destinationConnector_ = destinationConnector_;
      result.destinationWorker_ = destinationWorker_;
      result.tenant_ = tenant_;
      result.token_ = token_;
      result.context_ = context_;
      result.timeout_ = timeout_;
      result.timestamp_ = timestamp_;
      result.major_ = major_;
      result.minor_ = minor_;
      result.uUID_ = uUID_;
      result.connectorType_ = connectorType_;
      result.commandType_ = commandType_;
      result.command_ = command_;
      result.payload_ = payload_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ditrit.gandalf.java.grpc.CommandMessage) {
        return mergeFrom((com.ditrit.gandalf.java.grpc.CommandMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ditrit.gandalf.java.grpc.CommandMessage other) {
      if (other == com.ditrit.gandalf.java.grpc.CommandMessage.getDefaultInstance()) return this;
      if (!other.getSourceAggregator().isEmpty()) {
        sourceAggregator_ = other.sourceAggregator_;
        onChanged();
      }
      if (!other.getSourceConnector().isEmpty()) {
        sourceConnector_ = other.sourceConnector_;
        onChanged();
      }
      if (!other.getSourceWorker().isEmpty()) {
        sourceWorker_ = other.sourceWorker_;
        onChanged();
      }
      if (!other.getDestinationAggregator().isEmpty()) {
        destinationAggregator_ = other.destinationAggregator_;
        onChanged();
      }
      if (!other.getDestinationConnector().isEmpty()) {
        destinationConnector_ = other.destinationConnector_;
        onChanged();
      }
      if (!other.getDestinationWorker().isEmpty()) {
        destinationWorker_ = other.destinationWorker_;
        onChanged();
      }
      if (!other.getTenant().isEmpty()) {
        tenant_ = other.tenant_;
        onChanged();
      }
      if (!other.getToken().isEmpty()) {
        token_ = other.token_;
        onChanged();
      }
      if (!other.getContext().isEmpty()) {
        context_ = other.context_;
        onChanged();
      }
      if (!other.getTimeout().isEmpty()) {
        timeout_ = other.timeout_;
        onChanged();
      }
      if (!other.getTimestamp().isEmpty()) {
        timestamp_ = other.timestamp_;
        onChanged();
      }
      if (!other.getMajor().isEmpty()) {
        major_ = other.major_;
        onChanged();
      }
      if (!other.getMinor().isEmpty()) {
        minor_ = other.minor_;
        onChanged();
      }
      if (!other.getUUID().isEmpty()) {
        uUID_ = other.uUID_;
        onChanged();
      }
      if (!other.getConnectorType().isEmpty()) {
        connectorType_ = other.connectorType_;
        onChanged();
      }
      if (!other.getCommandType().isEmpty()) {
        commandType_ = other.commandType_;
        onChanged();
      }
      if (!other.getCommand().isEmpty()) {
        command_ = other.command_;
        onChanged();
      }
      if (!other.getPayload().isEmpty()) {
        payload_ = other.payload_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ditrit.gandalf.java.grpc.CommandMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ditrit.gandalf.java.grpc.CommandMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object sourceAggregator_ = "";
    /**
     * <code>optional string SourceAggregator = 1;</code>
     */
    public java.lang.String getSourceAggregator() {
      java.lang.Object ref = sourceAggregator_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceAggregator_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string SourceAggregator = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSourceAggregatorBytes() {
      java.lang.Object ref = sourceAggregator_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceAggregator_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string SourceAggregator = 1;</code>
     */
    public Builder setSourceAggregator(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sourceAggregator_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string SourceAggregator = 1;</code>
     */
    public Builder clearSourceAggregator() {
      
      sourceAggregator_ = getDefaultInstance().getSourceAggregator();
      onChanged();
      return this;
    }
    /**
     * <code>optional string SourceAggregator = 1;</code>
     */
    public Builder setSourceAggregatorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sourceAggregator_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sourceConnector_ = "";
    /**
     * <code>optional string SourceConnector = 2;</code>
     */
    public java.lang.String getSourceConnector() {
      java.lang.Object ref = sourceConnector_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceConnector_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string SourceConnector = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSourceConnectorBytes() {
      java.lang.Object ref = sourceConnector_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceConnector_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string SourceConnector = 2;</code>
     */
    public Builder setSourceConnector(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sourceConnector_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string SourceConnector = 2;</code>
     */
    public Builder clearSourceConnector() {
      
      sourceConnector_ = getDefaultInstance().getSourceConnector();
      onChanged();
      return this;
    }
    /**
     * <code>optional string SourceConnector = 2;</code>
     */
    public Builder setSourceConnectorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sourceConnector_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sourceWorker_ = "";
    /**
     * <code>optional string SourceWorker = 3;</code>
     */
    public java.lang.String getSourceWorker() {
      java.lang.Object ref = sourceWorker_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceWorker_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string SourceWorker = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSourceWorkerBytes() {
      java.lang.Object ref = sourceWorker_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceWorker_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string SourceWorker = 3;</code>
     */
    public Builder setSourceWorker(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sourceWorker_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string SourceWorker = 3;</code>
     */
    public Builder clearSourceWorker() {
      
      sourceWorker_ = getDefaultInstance().getSourceWorker();
      onChanged();
      return this;
    }
    /**
     * <code>optional string SourceWorker = 3;</code>
     */
    public Builder setSourceWorkerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sourceWorker_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object destinationAggregator_ = "";
    /**
     * <code>optional string DestinationAggregator = 4;</code>
     */
    public java.lang.String getDestinationAggregator() {
      java.lang.Object ref = destinationAggregator_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destinationAggregator_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string DestinationAggregator = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDestinationAggregatorBytes() {
      java.lang.Object ref = destinationAggregator_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destinationAggregator_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string DestinationAggregator = 4;</code>
     */
    public Builder setDestinationAggregator(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      destinationAggregator_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string DestinationAggregator = 4;</code>
     */
    public Builder clearDestinationAggregator() {
      
      destinationAggregator_ = getDefaultInstance().getDestinationAggregator();
      onChanged();
      return this;
    }
    /**
     * <code>optional string DestinationAggregator = 4;</code>
     */
    public Builder setDestinationAggregatorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      destinationAggregator_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object destinationConnector_ = "";
    /**
     * <code>optional string DestinationConnector = 5;</code>
     */
    public java.lang.String getDestinationConnector() {
      java.lang.Object ref = destinationConnector_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destinationConnector_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string DestinationConnector = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDestinationConnectorBytes() {
      java.lang.Object ref = destinationConnector_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destinationConnector_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string DestinationConnector = 5;</code>
     */
    public Builder setDestinationConnector(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      destinationConnector_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string DestinationConnector = 5;</code>
     */
    public Builder clearDestinationConnector() {
      
      destinationConnector_ = getDefaultInstance().getDestinationConnector();
      onChanged();
      return this;
    }
    /**
     * <code>optional string DestinationConnector = 5;</code>
     */
    public Builder setDestinationConnectorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      destinationConnector_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object destinationWorker_ = "";
    /**
     * <code>optional string DestinationWorker = 6;</code>
     */
    public java.lang.String getDestinationWorker() {
      java.lang.Object ref = destinationWorker_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destinationWorker_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string DestinationWorker = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDestinationWorkerBytes() {
      java.lang.Object ref = destinationWorker_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destinationWorker_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string DestinationWorker = 6;</code>
     */
    public Builder setDestinationWorker(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      destinationWorker_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string DestinationWorker = 6;</code>
     */
    public Builder clearDestinationWorker() {
      
      destinationWorker_ = getDefaultInstance().getDestinationWorker();
      onChanged();
      return this;
    }
    /**
     * <code>optional string DestinationWorker = 6;</code>
     */
    public Builder setDestinationWorkerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      destinationWorker_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object tenant_ = "";
    /**
     * <code>optional string Tenant = 7;</code>
     */
    public java.lang.String getTenant() {
      java.lang.Object ref = tenant_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tenant_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string Tenant = 7;</code>
     */
    public com.google.protobuf.ByteString
        getTenantBytes() {
      java.lang.Object ref = tenant_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenant_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string Tenant = 7;</code>
     */
    public Builder setTenant(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tenant_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string Tenant = 7;</code>
     */
    public Builder clearTenant() {
      
      tenant_ = getDefaultInstance().getTenant();
      onChanged();
      return this;
    }
    /**
     * <code>optional string Tenant = 7;</code>
     */
    public Builder setTenantBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tenant_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object token_ = "";
    /**
     * <code>optional string Token = 8;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string Token = 8;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string Token = 8;</code>
     */
    public Builder setToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      token_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string Token = 8;</code>
     */
    public Builder clearToken() {
      
      token_ = getDefaultInstance().getToken();
      onChanged();
      return this;
    }
    /**
     * <code>optional string Token = 8;</code>
     */
    public Builder setTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      token_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object context_ = "";
    /**
     * <code>optional string Context = 9;</code>
     */
    public java.lang.String getContext() {
      java.lang.Object ref = context_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        context_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string Context = 9;</code>
     */
    public com.google.protobuf.ByteString
        getContextBytes() {
      java.lang.Object ref = context_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        context_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string Context = 9;</code>
     */
    public Builder setContext(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      context_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string Context = 9;</code>
     */
    public Builder clearContext() {
      
      context_ = getDefaultInstance().getContext();
      onChanged();
      return this;
    }
    /**
     * <code>optional string Context = 9;</code>
     */
    public Builder setContextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      context_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object timeout_ = "";
    /**
     * <code>optional string Timeout = 10;</code>
     */
    public java.lang.String getTimeout() {
      java.lang.Object ref = timeout_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timeout_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string Timeout = 10;</code>
     */
    public com.google.protobuf.ByteString
        getTimeoutBytes() {
      java.lang.Object ref = timeout_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeout_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string Timeout = 10;</code>
     */
    public Builder setTimeout(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      timeout_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string Timeout = 10;</code>
     */
    public Builder clearTimeout() {
      
      timeout_ = getDefaultInstance().getTimeout();
      onChanged();
      return this;
    }
    /**
     * <code>optional string Timeout = 10;</code>
     */
    public Builder setTimeoutBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      timeout_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object timestamp_ = "";
    /**
     * <code>optional string Timestamp = 11;</code>
     */
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timestamp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string Timestamp = 11;</code>
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string Timestamp = 11;</code>
     */
    public Builder setTimestamp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string Timestamp = 11;</code>
     */
    public Builder clearTimestamp() {
      
      timestamp_ = getDefaultInstance().getTimestamp();
      onChanged();
      return this;
    }
    /**
     * <code>optional string Timestamp = 11;</code>
     */
    public Builder setTimestampBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      timestamp_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object major_ = "";
    /**
     * <code>optional string Major = 12;</code>
     */
    public java.lang.String getMajor() {
      java.lang.Object ref = major_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        major_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string Major = 12;</code>
     */
    public com.google.protobuf.ByteString
        getMajorBytes() {
      java.lang.Object ref = major_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        major_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string Major = 12;</code>
     */
    public Builder setMajor(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      major_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string Major = 12;</code>
     */
    public Builder clearMajor() {
      
      major_ = getDefaultInstance().getMajor();
      onChanged();
      return this;
    }
    /**
     * <code>optional string Major = 12;</code>
     */
    public Builder setMajorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      major_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object minor_ = "";
    /**
     * <code>optional string Minor = 13;</code>
     */
    public java.lang.String getMinor() {
      java.lang.Object ref = minor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        minor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string Minor = 13;</code>
     */
    public com.google.protobuf.ByteString
        getMinorBytes() {
      java.lang.Object ref = minor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        minor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string Minor = 13;</code>
     */
    public Builder setMinor(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      minor_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string Minor = 13;</code>
     */
    public Builder clearMinor() {
      
      minor_ = getDefaultInstance().getMinor();
      onChanged();
      return this;
    }
    /**
     * <code>optional string Minor = 13;</code>
     */
    public Builder setMinorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      minor_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object uUID_ = "";
    /**
     * <code>optional string UUID = 14;</code>
     */
    public java.lang.String getUUID() {
      java.lang.Object ref = uUID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uUID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string UUID = 14;</code>
     */
    public com.google.protobuf.ByteString
        getUUIDBytes() {
      java.lang.Object ref = uUID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uUID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string UUID = 14;</code>
     */
    public Builder setUUID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      uUID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string UUID = 14;</code>
     */
    public Builder clearUUID() {
      
      uUID_ = getDefaultInstance().getUUID();
      onChanged();
      return this;
    }
    /**
     * <code>optional string UUID = 14;</code>
     */
    public Builder setUUIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      uUID_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object connectorType_ = "";
    /**
     * <code>optional string ConnectorType = 15;</code>
     */
    public java.lang.String getConnectorType() {
      java.lang.Object ref = connectorType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        connectorType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string ConnectorType = 15;</code>
     */
    public com.google.protobuf.ByteString
        getConnectorTypeBytes() {
      java.lang.Object ref = connectorType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        connectorType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string ConnectorType = 15;</code>
     */
    public Builder setConnectorType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      connectorType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string ConnectorType = 15;</code>
     */
    public Builder clearConnectorType() {
      
      connectorType_ = getDefaultInstance().getConnectorType();
      onChanged();
      return this;
    }
    /**
     * <code>optional string ConnectorType = 15;</code>
     */
    public Builder setConnectorTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      connectorType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object commandType_ = "";
    /**
     * <code>optional string CommandType = 16;</code>
     */
    public java.lang.String getCommandType() {
      java.lang.Object ref = commandType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        commandType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string CommandType = 16;</code>
     */
    public com.google.protobuf.ByteString
        getCommandTypeBytes() {
      java.lang.Object ref = commandType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        commandType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string CommandType = 16;</code>
     */
    public Builder setCommandType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      commandType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string CommandType = 16;</code>
     */
    public Builder clearCommandType() {
      
      commandType_ = getDefaultInstance().getCommandType();
      onChanged();
      return this;
    }
    /**
     * <code>optional string CommandType = 16;</code>
     */
    public Builder setCommandTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      commandType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object command_ = "";
    /**
     * <code>optional string Command = 17;</code>
     */
    public java.lang.String getCommand() {
      java.lang.Object ref = command_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        command_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string Command = 17;</code>
     */
    public com.google.protobuf.ByteString
        getCommandBytes() {
      java.lang.Object ref = command_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        command_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string Command = 17;</code>
     */
    public Builder setCommand(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      command_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string Command = 17;</code>
     */
    public Builder clearCommand() {
      
      command_ = getDefaultInstance().getCommand();
      onChanged();
      return this;
    }
    /**
     * <code>optional string Command = 17;</code>
     */
    public Builder setCommandBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      command_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object payload_ = "";
    /**
     * <code>optional string Payload = 18;</code>
     */
    public java.lang.String getPayload() {
      java.lang.Object ref = payload_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        payload_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string Payload = 18;</code>
     */
    public com.google.protobuf.ByteString
        getPayloadBytes() {
      java.lang.Object ref = payload_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        payload_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string Payload = 18;</code>
     */
    public Builder setPayload(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      payload_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string Payload = 18;</code>
     */
    public Builder clearPayload() {
      
      payload_ = getDefaultInstance().getPayload();
      onChanged();
      return this;
    }
    /**
     * <code>optional string Payload = 18;</code>
     */
    public Builder setPayloadBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      payload_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:grpc.CommandMessage)
  }

  // @@protoc_insertion_point(class_scope:grpc.CommandMessage)
  private static final com.ditrit.gandalf.java.grpc.CommandMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ditrit.gandalf.java.grpc.CommandMessage();
  }

  public static com.ditrit.gandalf.java.grpc.CommandMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CommandMessage>
      PARSER = new com.google.protobuf.AbstractParser<CommandMessage>() {
    public CommandMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new CommandMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CommandMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CommandMessage> getParserForType() {
    return PARSER;
  }

  public com.ditrit.gandalf.java.grpc.CommandMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

