// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connectorCommand.proto

package com.ditrit.gandalf.java.grpc;

public interface CommandMessageUUIDOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.CommandMessageUUID)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string UUID = 1;</code>
   */
  java.lang.String getUUID();
  /**
   * <code>optional string UUID = 1;</code>
   */
  com.google.protobuf.ByteString
      getUUIDBytes();
}
