// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connectorCommand.proto

package com.ditrit.gandalf.java.grpc;

public final class ConnectorCommandProto {
  private ConnectorCommandProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_CommandMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_CommandMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_CommandMessageUUID_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_CommandMessageUUID_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_CommandMessageWait_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_CommandMessageWait_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_CommandMessageReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_CommandMessageReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026connectorCommand.proto\022\004grpc\032\017connecto" +
      "r.proto\"\377\002\n\016CommandMessage\022\030\n\020SourceAggr" +
      "egator\030\001 \001(\t\022\027\n\017SourceConnector\030\002 \001(\t\022\024\n" +
      "\014SourceWorker\030\003 \001(\t\022\035\n\025DestinationAggreg" +
      "ator\030\004 \001(\t\022\034\n\024DestinationConnector\030\005 \001(\t" +
      "\022\031\n\021DestinationWorker\030\006 \001(\t\022\016\n\006Tenant\030\007 " +
      "\001(\t\022\r\n\005Token\030\010 \001(\t\022\017\n\007Context\030\t \001(\t\022\017\n\007T" +
      "imeout\030\n \001(\t\022\021\n\tTimestamp\030\013 \001(\t\022\r\n\005Major" +
      "\030\014 \001(\t\022\r\n\005Minor\030\r \001(\t\022\014\n\004UUID\030\016 \001(\t\022\025\n\rC" +
      "onnectorType\030\017 \001(\t\022\023\n\013CommandType\030\020 \001(\t\022",
      "\017\n\007Command\030\021 \001(\t\022\017\n\007Payload\030\022 \001(\t\"\"\n\022Com" +
      "mandMessageUUID\022\014\n\004UUID\030\001 \001(\t\"M\n\022Command" +
      "MessageWait\022\024\n\014WorkerSource\030\001 \001(\t\022\r\n\005Val" +
      "ue\030\002 \001(\t\022\022\n\nIteratorId\030\003 \001(\t\"\270\002\n\023Command" +
      "MessageReply\022\030\n\020SourceAggregator\030\001 \001(\t\022\027" +
      "\n\017SourceConnector\030\002 \001(\t\022\024\n\014SourceWorker\030" +
      "\003 \001(\t\022\035\n\025DestinationAggregator\030\004 \001(\t\022\034\n\024" +
      "DestinationConnector\030\005 \001(\t\022\031\n\021Destinatio" +
      "nWorker\030\006 \001(\t\022\016\n\006Tenant\030\007 \001(\t\022\r\n\005Token\030\010" +
      " \001(\t\022\017\n\007Context\030\t \001(\t\022\017\n\007Timeout\030\n \001(\t\022\021",
      "\n\tTimestamp\030\013 \001(\t\022\014\n\004UUID\030\014 \001(\t\022\r\n\005Reply" +
      "\030\r \001(\t\022\017\n\007Payload\030\016 \001(\t2\370\002\n\020ConnectorCom" +
      "mand\022F\n\022SendCommandMessage\022\024.grpc.Comman" +
      "dMessage\032\030.grpc.CommandMessageUUID\"\000\022C\n\027" +
      "SendCommandMessageReply\022\031.grpc.CommandMe" +
      "ssageReply\032\013.grpc.Empty\"\000\022F\n\022WaitCommand" +
      "Message\022\030.grpc.CommandMessageWait\032\024.grpc" +
      ".CommandMessage\"\000\022P\n\027WaitCommandMessageR" +
      "eply\022\030.grpc.CommandMessageWait\032\031.grpc.Co" +
      "mmandMessageReply\"\000\022=\n\025CreateIteratorCom",
      "mand\022\013.grpc.Empty\032\025.grpc.IteratorMessage" +
      "\"\000B7\n\034com.ditrit.gandalf.java.grpcB\025Conn" +
      "ectorCommandProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ditrit.gandalf.java.grpc.ConnectorProto.getDescriptor(),
        }, assigner);
    internal_static_grpc_CommandMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_CommandMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_CommandMessage_descriptor,
        new java.lang.String[] { "SourceAggregator", "SourceConnector", "SourceWorker", "DestinationAggregator", "DestinationConnector", "DestinationWorker", "Tenant", "Token", "Context", "Timeout", "Timestamp", "Major", "Minor", "UUID", "ConnectorType", "CommandType", "Command", "Payload", });
    internal_static_grpc_CommandMessageUUID_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_CommandMessageUUID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_CommandMessageUUID_descriptor,
        new java.lang.String[] { "UUID", });
    internal_static_grpc_CommandMessageWait_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_grpc_CommandMessageWait_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_CommandMessageWait_descriptor,
        new java.lang.String[] { "WorkerSource", "Value", "IteratorId", });
    internal_static_grpc_CommandMessageReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_grpc_CommandMessageReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_CommandMessageReply_descriptor,
        new java.lang.String[] { "SourceAggregator", "SourceConnector", "SourceWorker", "DestinationAggregator", "DestinationConnector", "DestinationWorker", "Tenant", "Token", "Context", "Timeout", "Timestamp", "UUID", "Reply", "Payload", });
    com.ditrit.gandalf.java.grpc.ConnectorProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
