// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connectorEvent.proto

package com.ditrit.gandalf.java.grpc;

/**
 * Protobuf type {@code grpc.EventMessageWait}
 */
public  final class EventMessageWait extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.EventMessageWait)
    EventMessageWaitOrBuilder {
  // Use EventMessageWait.newBuilder() to construct.
  private EventMessageWait(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EventMessageWait() {
    workerSource_ = "";
    event_ = "";
    topic_ = "";
    iteratorId_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private EventMessageWait(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            workerSource_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            event_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            topic_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            iteratorId_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ditrit.gandalf.java.grpc.ConnectorEventProto.internal_static_grpc_EventMessageWait_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ditrit.gandalf.java.grpc.ConnectorEventProto.internal_static_grpc_EventMessageWait_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ditrit.gandalf.java.grpc.EventMessageWait.class, com.ditrit.gandalf.java.grpc.EventMessageWait.Builder.class);
  }

  public static final int WORKERSOURCE_FIELD_NUMBER = 1;
  private volatile java.lang.Object workerSource_;
  /**
   * <code>optional string WorkerSource = 1;</code>
   */
  public java.lang.String getWorkerSource() {
    java.lang.Object ref = workerSource_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      workerSource_ = s;
      return s;
    }
  }
  /**
   * <code>optional string WorkerSource = 1;</code>
   */
  public com.google.protobuf.ByteString
      getWorkerSourceBytes() {
    java.lang.Object ref = workerSource_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      workerSource_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EVENT_FIELD_NUMBER = 2;
  private volatile java.lang.Object event_;
  /**
   * <code>optional string Event = 2;</code>
   */
  public java.lang.String getEvent() {
    java.lang.Object ref = event_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      event_ = s;
      return s;
    }
  }
  /**
   * <code>optional string Event = 2;</code>
   */
  public com.google.protobuf.ByteString
      getEventBytes() {
    java.lang.Object ref = event_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      event_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOPIC_FIELD_NUMBER = 3;
  private volatile java.lang.Object topic_;
  /**
   * <code>optional string Topic = 3;</code>
   */
  public java.lang.String getTopic() {
    java.lang.Object ref = topic_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      topic_ = s;
      return s;
    }
  }
  /**
   * <code>optional string Topic = 3;</code>
   */
  public com.google.protobuf.ByteString
      getTopicBytes() {
    java.lang.Object ref = topic_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      topic_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ITERATORID_FIELD_NUMBER = 4;
  private volatile java.lang.Object iteratorId_;
  /**
   * <code>optional string IteratorId = 4;</code>
   */
  public java.lang.String getIteratorId() {
    java.lang.Object ref = iteratorId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      iteratorId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string IteratorId = 4;</code>
   */
  public com.google.protobuf.ByteString
      getIteratorIdBytes() {
    java.lang.Object ref = iteratorId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      iteratorId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getWorkerSourceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, workerSource_);
    }
    if (!getEventBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, event_);
    }
    if (!getTopicBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, topic_);
    }
    if (!getIteratorIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, iteratorId_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getWorkerSourceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, workerSource_);
    }
    if (!getEventBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, event_);
    }
    if (!getTopicBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, topic_);
    }
    if (!getIteratorIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, iteratorId_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ditrit.gandalf.java.grpc.EventMessageWait)) {
      return super.equals(obj);
    }
    com.ditrit.gandalf.java.grpc.EventMessageWait other = (com.ditrit.gandalf.java.grpc.EventMessageWait) obj;

    boolean result = true;
    result = result && getWorkerSource()
        .equals(other.getWorkerSource());
    result = result && getEvent()
        .equals(other.getEvent());
    result = result && getTopic()
        .equals(other.getTopic());
    result = result && getIteratorId()
        .equals(other.getIteratorId());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + WORKERSOURCE_FIELD_NUMBER;
    hash = (53 * hash) + getWorkerSource().hashCode();
    hash = (37 * hash) + EVENT_FIELD_NUMBER;
    hash = (53 * hash) + getEvent().hashCode();
    hash = (37 * hash) + TOPIC_FIELD_NUMBER;
    hash = (53 * hash) + getTopic().hashCode();
    hash = (37 * hash) + ITERATORID_FIELD_NUMBER;
    hash = (53 * hash) + getIteratorId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ditrit.gandalf.java.grpc.EventMessageWait parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ditrit.gandalf.java.grpc.EventMessageWait parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ditrit.gandalf.java.grpc.EventMessageWait parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ditrit.gandalf.java.grpc.EventMessageWait parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ditrit.gandalf.java.grpc.EventMessageWait parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ditrit.gandalf.java.grpc.EventMessageWait parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ditrit.gandalf.java.grpc.EventMessageWait parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ditrit.gandalf.java.grpc.EventMessageWait parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ditrit.gandalf.java.grpc.EventMessageWait parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ditrit.gandalf.java.grpc.EventMessageWait parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ditrit.gandalf.java.grpc.EventMessageWait prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpc.EventMessageWait}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.EventMessageWait)
      com.ditrit.gandalf.java.grpc.EventMessageWaitOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ditrit.gandalf.java.grpc.ConnectorEventProto.internal_static_grpc_EventMessageWait_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ditrit.gandalf.java.grpc.ConnectorEventProto.internal_static_grpc_EventMessageWait_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ditrit.gandalf.java.grpc.EventMessageWait.class, com.ditrit.gandalf.java.grpc.EventMessageWait.Builder.class);
    }

    // Construct using com.ditrit.gandalf.java.grpc.EventMessageWait.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      workerSource_ = "";

      event_ = "";

      topic_ = "";

      iteratorId_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ditrit.gandalf.java.grpc.ConnectorEventProto.internal_static_grpc_EventMessageWait_descriptor;
    }

    public com.ditrit.gandalf.java.grpc.EventMessageWait getDefaultInstanceForType() {
      return com.ditrit.gandalf.java.grpc.EventMessageWait.getDefaultInstance();
    }

    public com.ditrit.gandalf.java.grpc.EventMessageWait build() {
      com.ditrit.gandalf.java.grpc.EventMessageWait result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.ditrit.gandalf.java.grpc.EventMessageWait buildPartial() {
      com.ditrit.gandalf.java.grpc.EventMessageWait result = new com.ditrit.gandalf.java.grpc.EventMessageWait(this);
      result.workerSource_ = workerSource_;
      result.event_ = event_;
      result.topic_ = topic_;
      result.iteratorId_ = iteratorId_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ditrit.gandalf.java.grpc.EventMessageWait) {
        return mergeFrom((com.ditrit.gandalf.java.grpc.EventMessageWait)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ditrit.gandalf.java.grpc.EventMessageWait other) {
      if (other == com.ditrit.gandalf.java.grpc.EventMessageWait.getDefaultInstance()) return this;
      if (!other.getWorkerSource().isEmpty()) {
        workerSource_ = other.workerSource_;
        onChanged();
      }
      if (!other.getEvent().isEmpty()) {
        event_ = other.event_;
        onChanged();
      }
      if (!other.getTopic().isEmpty()) {
        topic_ = other.topic_;
        onChanged();
      }
      if (!other.getIteratorId().isEmpty()) {
        iteratorId_ = other.iteratorId_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ditrit.gandalf.java.grpc.EventMessageWait parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ditrit.gandalf.java.grpc.EventMessageWait) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object workerSource_ = "";
    /**
     * <code>optional string WorkerSource = 1;</code>
     */
    public java.lang.String getWorkerSource() {
      java.lang.Object ref = workerSource_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        workerSource_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string WorkerSource = 1;</code>
     */
    public com.google.protobuf.ByteString
        getWorkerSourceBytes() {
      java.lang.Object ref = workerSource_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        workerSource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string WorkerSource = 1;</code>
     */
    public Builder setWorkerSource(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      workerSource_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string WorkerSource = 1;</code>
     */
    public Builder clearWorkerSource() {
      
      workerSource_ = getDefaultInstance().getWorkerSource();
      onChanged();
      return this;
    }
    /**
     * <code>optional string WorkerSource = 1;</code>
     */
    public Builder setWorkerSourceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      workerSource_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object event_ = "";
    /**
     * <code>optional string Event = 2;</code>
     */
    public java.lang.String getEvent() {
      java.lang.Object ref = event_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        event_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string Event = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEventBytes() {
      java.lang.Object ref = event_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        event_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string Event = 2;</code>
     */
    public Builder setEvent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      event_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string Event = 2;</code>
     */
    public Builder clearEvent() {
      
      event_ = getDefaultInstance().getEvent();
      onChanged();
      return this;
    }
    /**
     * <code>optional string Event = 2;</code>
     */
    public Builder setEventBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      event_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object topic_ = "";
    /**
     * <code>optional string Topic = 3;</code>
     */
    public java.lang.String getTopic() {
      java.lang.Object ref = topic_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topic_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string Topic = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTopicBytes() {
      java.lang.Object ref = topic_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string Topic = 3;</code>
     */
    public Builder setTopic(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      topic_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string Topic = 3;</code>
     */
    public Builder clearTopic() {
      
      topic_ = getDefaultInstance().getTopic();
      onChanged();
      return this;
    }
    /**
     * <code>optional string Topic = 3;</code>
     */
    public Builder setTopicBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      topic_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object iteratorId_ = "";
    /**
     * <code>optional string IteratorId = 4;</code>
     */
    public java.lang.String getIteratorId() {
      java.lang.Object ref = iteratorId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        iteratorId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string IteratorId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getIteratorIdBytes() {
      java.lang.Object ref = iteratorId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        iteratorId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string IteratorId = 4;</code>
     */
    public Builder setIteratorId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      iteratorId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string IteratorId = 4;</code>
     */
    public Builder clearIteratorId() {
      
      iteratorId_ = getDefaultInstance().getIteratorId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string IteratorId = 4;</code>
     */
    public Builder setIteratorIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      iteratorId_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:grpc.EventMessageWait)
  }

  // @@protoc_insertion_point(class_scope:grpc.EventMessageWait)
  private static final com.ditrit.gandalf.java.grpc.EventMessageWait DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ditrit.gandalf.java.grpc.EventMessageWait();
  }

  public static com.ditrit.gandalf.java.grpc.EventMessageWait getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EventMessageWait>
      PARSER = new com.google.protobuf.AbstractParser<EventMessageWait>() {
    public EventMessageWait parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new EventMessageWait(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EventMessageWait> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EventMessageWait> getParserForType() {
    return PARSER;
  }

  public com.ditrit.gandalf.java.grpc.EventMessageWait getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

