// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connectorEvent.proto

package com.ditrit.gandalf.java.grpc;

public interface EventMessageWaitOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.EventMessageWait)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string WorkerSource = 1;</code>
   */
  java.lang.String getWorkerSource();
  /**
   * <code>optional string WorkerSource = 1;</code>
   */
  com.google.protobuf.ByteString
      getWorkerSourceBytes();

  /**
   * <code>optional string Event = 2;</code>
   */
  java.lang.String getEvent();
  /**
   * <code>optional string Event = 2;</code>
   */
  com.google.protobuf.ByteString
      getEventBytes();

  /**
   * <code>optional string Topic = 3;</code>
   */
  java.lang.String getTopic();
  /**
   * <code>optional string Topic = 3;</code>
   */
  com.google.protobuf.ByteString
      getTopicBytes();

  /**
   * <code>optional string IteratorId = 4;</code>
   */
  java.lang.String getIteratorId();
  /**
   * <code>optional string IteratorId = 4;</code>
   */
  com.google.protobuf.ByteString
      getIteratorIdBytes();
}
