key1:
  name: tenant
  type: string
  description: value of the tenant
  default: tenant1
  short_name: t
key2:
  name: category
  type: string
  description: value of the category
  default: bus
  short_name: c
key3:
  name: product
  type: string
  description: value of the product
  default: kafka
  short_name: p
key4:
  name: aggregators
  type: string
  description: value of the aggregators IP
  default: address1[:port],address2[:port]
  short_name: a
